name: 'PR Slack Reminder'
description: 'Sends a Slack reminder about open PRs'
runs:
  using: 'node20'
  main: 'invoke-binary.js'
branding:
  icon: 'git-pull-request'
  color: 'green'
inputs: {
  slack-bot-token: {
    description: 'Slack bot token to send the message via (the bot must be a member of the channel)',
    required: true,
  },
  github-token: {
    description: 'GitHub token to access the repository',
    required: true,
  },
  github-token-for-state: {
    description: 'GitHub token that has read access to artifacts of the current repository (i.e. actions: read). Only needed if the run-mode is `update` and if the default github-token misses permissions.',
    required: true,
  },
  run-mode: {
    description: 'Run mode: post (default) posts a new reminder; update refreshes an existing reminder',
    required: false,
    default: 'post',
  },
  state-artifact-name: {
    description: 'Name of the artifact containing state from previous runs (required when run-mode is update)',
    required: false,
    default: 'pr-slack-reminder-state',
  },
  slack-channel-name: {
    description: 'Slack channel name to send the message to',
    required: false,
  },
  slack-channel-id: {
    description: 'Slack channel ID to send the message to',
    required: false,
  },
  github-repositories: {
    description: 'Line break separated list of GitHub repositories (max 30) to check for open PRs. If not provided, the repository of the current workflow run will be used.',
    required: false,
  },
  filters: {
    description: 'Global filters (e.g. {"authors": ["alice", "bob"], "labels": ["bug", "enhancement"], "ignored-labels": ["wip"], "ignored-terms": ["WIP"]})',
    required: false,
  },
  repository-filters: {
    description: 'Repository-specific filters (e.g., "repo1: {"authors-ignore": ["alice"]}; repo2: {"labels": ["bug"]})',
    required: false,
  },
  github-user-slack-user-id-mapping: {
    description: 'Mapping of GitHub usernames to Slack user IDs (e.g., "alice: U08RWPGNCUX\\nbob: U08RWPGNWER")',
    required: false,
  },
  pr-list-heading: {
    description: 'Main heading of the message to send (`<pr_count>` gets replaced)',
    required: false,
    default: 'There are <pr_count> open PRs 👀',
  },
  no-prs-message: {
    description: 'Message to send when there are no open PRs',
    required: false,
  },
  old-pr-threshold-hours: {
    description: 'PR age in hours after which a PR is highlighted as old (with alarm emoji and bold age text)',
    required: false,
    default: '96',
  },
  group-by-repository: {
    description: 'Group PRs by repository with repository headings. When enabled, pr-list-heading is ignored.',
    required: false,
    default: 'false',
  },
}
