name: 'Release'
description: 'Create a release tag with version bump'

inputs:
  semver:
    description: 'Whether to bump major, minor, or patch version'
    required: true

runs:
  using: composite
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Bump version & create tagged release
      shell: bash
      run: |
        echo "SEMVER input: ${{ inputs.semver }}"
        make release-tag SEMVER="${{ inputs.semver }}"
