name: 'Publish Coverage'
description: 'Publish test coverage to Coveralls'

inputs:
  coveralls-token:
    description: 'Coveralls token for coverage reporting'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c #v6.1.0
      with:
        go-version: 1.25
        
    - name: Install goveralls
      shell: bash
      run: go install github.com/mattn/goveralls@v0.0.12
    
    - name: Publish coverage to Coveralls
      shell: bash
      env:
        COVERALLS_TOKEN: ${{ inputs.coveralls-token }}
      run: make publish-code-coverage
